### ISSUE TITLE
LibUv-exception under kind of heavy load

### ISSUE THREAD

**Issue by jmrnilsson** [jmrnilsson/MinMQ#20]
Uploading 50000 documents (JSON/XML) over 400 concurrent sockets crashed LibUv. Look into retries and/or _Managed sockets_.

```
> dotnet run 50000
Preparing payload
0%
0%
1%
1%
2%
...
99%
Done! 2 729,28 documents/s
Sending JSON and XML..Done! 4 507,73 documents/s
```

```
info: MinMQ.Service.Faster.FasterHostedServiceMoveData[0]
      Nothing to flush
info: MinMQ.Service.Faster.FasterHostedServiceCommit[0]
      Polling commits every 5 ms
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Connections.ConnectionResetException: Error -4077 ECONNRESET connection reset by peer
 ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync()
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at MinMQ.Service.HttpRequestHandlers.FasterHttpHandler.HandleRequest(HttpContext context) in M:\devwork\MinMQ\service\MinMQ.Service\HttpRequestHandlers\FasterHttpHandler.cs:line 16
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: MinMQ.Service.Faster.FasterHostedServiceCommit[0]
      Polling commits every 5 ms
info: MinMQ.Service.Faster.FasterHostedServiceMoveData[0]
      Nothing to flush
info: MinMQ.Service.Faster.FasterHostedServiceCommit[0]
      Polling commits every 5 ms
info: MinMQ.Service.Faster.FasterHostedServiceMoveData[0]
      Nothing to flush
```

**Comment by jmrnilsson** [comment]
Looks like debugger was on. Then this could be expected.
