### ISSUE TITLE
Postgres Socket drained

### ISSUE THREAD

**Issue by jmrnilsson** [jmrnilsson/MinMQ#27]
- When sending a few documents whilst running docker-compose.

```
mmq-service_1          |       An error occurred using the connection to database 'mmq' on server 'tcp://localhost:5432'.
mmq-service_1          | fail: Microsoft.EntityFrameworkCore.Query[10100]
mmq-service_1          |       An exception occurred while iterating over the results of a query for context type 'MinMq.Service.Models.MessageQueueContext'.
mmq-service_1          |       Npgsql.NpgsqlException (0x80004005): Exception while connecting
mmq-service_1          |        ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
mmq-service_1          |          at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
mmq-service_1          |          at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
mmq-service_1          |          at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
mmq-service_1          |          at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
mmq-service_1          |          at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
mmq-service_1          |          at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
mmq-service_1          |          at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
mmq-service_1          |          at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
mmq-service_1          |          at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
mmq-service_1          |          at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
mmq-service_1          |       --- End of stack trace from previous location where exception was thrown ---
mmq-service_1          |          at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
mmq-service_1          |          at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
mmq-service_1          |          at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
mmq-service_1          |          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
mmq-service_1          |          at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
mmq-service_1          | Npgsql.NpgsqlException (0x80004005): Exception while connecting
mmq-service_1          |  ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
mmq-service_1          |    at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
mmq-service_1          |    at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
mmq-service_1          |    at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
mmq-service_1          |    at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
mmq-service_1          |    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
mmq-service_1          |    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
mmq-service_1          |    at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
mmq-service_1          |    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
mmq-service_1          |    at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
mmq-service_1          |    at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
mmq-service_1          | --- End of stack trace from previous location where exception was thrown ---
mmq-service_1          |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
mmq-service_1          |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
mmq-service_1          |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
mmq-service_1          |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
mmq-service_1          |    at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
mmq-service_1          | Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while connecting
mmq-service_1          |  ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
mmq-service_1          |    at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
mmq-service_1          |    at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
mmq-service_1          |    at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
mmq-service_1          |    at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
mmq-service_1          |    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
mmq-service_1          |    at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
mmq-service_1          |    at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
mmq-service_1          |    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
mmq-service_1          |    at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
mmq-service_1          |    at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
mmq-service_1          | --- End of stack trace from previous location where exception was thrown ---
mmq-service_1          |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
mmq-service_1          |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
mmq-service_1          |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
mmq-service_1          |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
mmq-service_1          |    at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
mmq-service_1          |    at System.Linq.AsyncEnumerable.WhereSelectEnumerableAsyncIterator`2.MoveNextCore() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\Where.cs:line 385
mmq-service_1          |    at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:line 70
mmq-service_1          |    at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:line 75
mmq-service_1          |    at System.Linq.AsyncEnumerable.<ToDictionaryAsync>g__Core|604_0[TSource,TKey](IAsyncEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToDictionary.cs:line 29
mmq-service_1          |    at System.Linq.AsyncEnumerable.<ToDictionaryAsync>g__Core|604_0[TSource,TKey](IAsyncEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToDictionary.cs:line 29
mmq-service_1          |    at MinMq.Service.Repository.MessageRepository.IntersectMessages(List`1 ids) in /src/Repository/MessageRepository.cs:line 86
mmq-service_1          |    at MinMq.Service.Repository.MessageRepository.AddRange(List`1 messages) in /src/Repository/MessageRepository.cs:line 27
mmq-service_1          |    at MinMQ.Service.Faster.FasterHostedServiceMoveData.StartAsync(CancellationToken stoppingToken) in /src/Faster/FasterHostedServiceMoveData.cs:line 57
mmq-service_1          |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
mmq-service_1          |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
mmq-service_1          |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
mmq-service_1          |    at MinMQ.Service.Program.Main(String[] args) in /src/Program.cs:line 37
mmq-service_1          |    at MinMQ.Service.Program.<Main>(String[] args)
```

**Comment by jmrnilsson** [comment]
Turns out connectionString had been replaced..
