### ISSUE TITLE
Some duplicate key to expect apparently 

### ISSUE THREAD

**Issue by jmrnilsson** [jmrnilsson/MinMQ#28]
Same key

```
mmq-service_1          | info: MinMQ.Service.Faster.FasterHostedServiceCommit[0]
mmq-service_1          |       Polling commits every 5 ms
mmq-service_1          | Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 64
mmq-service_1          |    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
mmq-service_1          |    at System.Linq.AsyncEnumerable.<ToDictionaryAsync>g__Core|604_0[TSource,TKey](IAsyncEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToDictionary.cs:line 29
mmq-service_1          |    at System.Linq.AsyncEnumerable.<ToDictionaryAsync>g__Core|604_0[TSource,TKey](IAsyncEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToDictionary.cs:line 29
mmq-service_1          |    at MinMq.Service.Repository.MessageRepository.IntersectMessages(List`1 ids) in /src/Repository/MessageRepository.cs:line 86
mmq-service_1          |    at MinMq.Service.Repository.MessageRepository.AddRange(List`1 messages) in /src/Repository/MessageRepository.cs:line 27
mmq-service_1          |    at MinMQ.Service.Faster.FasterHostedServiceMoveData.StartAsync(CancellationToken stoppingToken) in /src/Faster/FasterHostedServiceMoveData.cs:line 61
mmq-service_1          |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
mmq-service_1          |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
mmq-service_1          |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
mmq-service_1          |    at MinMQ.Service.Program.Main(String[] args) in /src/Program.cs:line 37
mmq-service_1          |    at MinMQ.Service.Program.<Main>(String[] args)
```

**Comment by jmrnilsson** [comment]
Closed in dev
