### ISSUE TITLE
rpi4 - async read body fails

### ISSUE THREAD

**Issue by jmrnilsson** [jmrnilsson/MinMQ#6]
mmq-service-kestrel_1  | fail: Microsoft.AspNetCore.Server.Kestrel[13]
mmq-service-kestrel_1  |       Connection id "0HLRGLGKTJIHB", Request id "0HLRGLGKTJIHB:0000000D": An unhandled exception was thrown by the application.
mmq-service-kestrel_1  | Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
mmq-service-kestrel_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
mmq-service-kestrel_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
mmq-service-kestrel_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
mmq-service-kestrel_1  |    at System.IO.StreamReader.ReadBufferAsync()
mmq-service-kestrel_1  |    at System.IO.StreamReader.ReadToEndAsyncInternal()
mmq-service-kestrel_1  |    at Service_Kestrel.RequestHandlers.FasterHttpHandler.HandleRequest(HttpContext context) in /src/RequestHandlers/FasterHandler.cs:line 35
mmq-service-kestrel_1  |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
mmq-service-kestrel_1  |    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
mmq-service-kestrel_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by jmrnilsson** [comment]
There might be need for a middleware that pauses request until the next flush instead. Or something like that.

- https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.0#scoped

**Comment by jmrnilsson** [comment]
Semaphore disabled on AMD64

```
mmq-service-kestrel_1  | info: Service_Kestrel.Faster.FasterCommitHostedService[0]
mmq-service-kestrel_1  |       Polling commits. state.InvokationCount % 600 == 0
mmq-service-kestrel_1  | Unhandled exception. Unhandled exception. System.Exception: Unable to add item to list
mmq-service-kestrel_1  |    at FASTER.core.PendingFlushList.Add(PageAsyncFlushResult`1 t)
mmq-service-kestrel_1  |    at FASTER.core.AllocatorBase`2.AsyncFlushPages(Int64 fromAddress, Int64 untilAddress)
mmq-service-kestrel_1  |    at FASTER.core.AllocatorBase`2.OnPagesMarkedReadOnly(Int64 newSafeReadOnlyAddress)
mmq-service-kestrel_1  |    at FASTER.core.AllocatorBase`2.<>c__DisplayClass88_0.<ShiftReadOnlyToTail>b__0()
mmq-service-kestrel_1  |    at FASTER.core.FasterLog.CommitInternal(Boolean spinWait)
mmq-service-kestrel_1  |    at FASTER.core.FasterLog.CommitAsync(CancellationToken token)
mmq-service-kestrel_1  |    at Service_Kestrel.FasterWriter.CommitAsync(CancellationToken token) in /src/Faster/FasterWriter.cs:line 26
mmq-service-kestrel_1  |    at Service_Kestrel.Faster.FasterCommitHostedService.ExecuteAsync(Object stateInfo) in /src/Faster/TimedFasterCommitService.cs:line 73
mmq-service-kestrel_1  |    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
mmq-service-kestrel_1  |    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
mmq-service-kestrel_1  |    at System.Threading.ThreadPoolWorkQueue.Dispatch()System.Exception: Unable to add item to list
mmq-service-kestrel_1  |    at FASTER.core.PendingFlushList.Add(PageAsyncFlushResult`1 t)
mmq-service-kestrel_1  |    at FASTER.core.AllocatorBase`2.AsyncFlushPages(Int64 fromAddress, Int64 untilAddress)
mmq-service-kestrel_1  |    at FASTER.core.AllocatorBase`2.OnPagesMarkedReadOnly(Int64 newSafeReadOnlyAddress)
mmq-service-kestrel_1  |    at FASTER.core.AllocatorBase`2.<>c__DisplayClass88_0.<ShiftReadOnlyToTail>b__0()
mmq-service-kestrel_1  |    at FASTER.core.FasterLog.CommitInternal(Boolean spinWait)
mmq-service-kestrel_1  |    at FASTER.core.FasterLog.CommitAsync(CancellationToken token)
mmq-service-kestrel_1  |    at Service_Kestrel.FasterWriter.CommitAsync(CancellationToken token) in /src/Faster/FasterWriter.cs:line 26
mmq-service-kestrel_1  |    at Service_Kestrel.Faster.FasterCommitHostedService.ExecuteAsync(Object stateInfo) in /src/Faster/TimedFasterCommitService.cs:line 73
mmq-service-kestrel_1  |    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
mmq-service-kestrel_1  |    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
mmq-service-kestrel_1  |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
mmq-service-kestrel_1  |
```

**Comment by jmrnilsson** [comment]
#blurp, debian duster automatically downgraded from V8L to V7L.. why?
